# Generated by Django 5.2 on 2025-04-09 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0005_remove_user_address_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoginAttempt',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
