# Generated by Django 5.2 on 2025-04-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0009_menu_user_address_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
