# Generated by Django 5.2 on 2025-04-25 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0010_menu_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_in_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feast.menu'),
        ),
    ]
