# Generated by Django 5.2 on 2025-04-25 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0011_order_is_in_option_alter_order_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feast.menu'),
            preserve_default=False,
        ),
    ]
