# Generated by Django 5.2 on 2025-04-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0013_user_payment_status_inattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_status',
        ),
        migrations.DeleteModel(
            name='InAttendance',
        ),
    ]
