# Generated by Django 5.2 on 2025-05-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0014_remove_user_payment_status_delete_inattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('college', 'College'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
