# Generated by Django 5.2 on 2025-05-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0015_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('college_admin', 'College Admin'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
