# Generated by Django 5.2 on 2025-05-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0016_user_college_alter_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='college',
            new_name='college_admin',
        ),
    ]
