# Generated by Django 5.2 on 2025-05-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0017_rename_college_user_college_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='college_admin',
        ),
    ]
