# Generated by Django 5.2 on 2025-05-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0018_remove_user_college_admin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
