# Generated by Django 5.2 on 2025-05-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0023_user_expense'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='expense_added',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
