# Generated by Django 5.2 on 2025-05-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0024_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='expense_added',
        ),
    ]
