# Generated by Django 5.2 on 2025-05-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast', '0025_alter_attendance_unique_together_remove_user_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
